AWSTemplateFormatVersion: '2010-09-09'
Description: Template for sportnumerics explorer cloudfront distribution
Parameters:
  StageParameter:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
    Description: Stage to deploy
  ExplorerStageDeployment:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prodblue
    - prodgreen
Mappings:
  StageMapping:
    dev:
      aliases:
      - dev.sportnumerics.com
      certificate: arn:aws:acm:us-east-1:265978616089:certificate/8a8d8c31-20b3-49c4-8b58-13b259064cc6
    prod:
      aliases:
      - sportnumerics.com
      - www.sportnumerics.com
      - prod.sportnumerics.com
      certificate: arn:aws:acm:us-east-1:265978616089:certificate/7140c26c-5b35-4f21-b16d-695bf5a659e6
Resources:
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          Fn::FindInMap:
          - StageMapping
          - Ref: StageParameter
          - aliases
        CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: DefaultOrigin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
        DefaultRootObject: index.html
        Enabled: true
        Origins:
        - DomainName:
            Fn::Join:
            - "."
            - - Fn::Join:
                - "-"
                - - sportnumerics-explorer
                  - Ref: ExplorerStageDeployment
              - s3.amazonaws.com
          Id: DefaultOrigin
          S3OriginConfig: {}
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn:
            Fn::FindInMap:
              - StageMapping
              - Ref: StageParameter
              - certificate
          SslSupportMethod: sni-only
Outputs:
  CloudfrontArn:
    Description: Cloudfront distribution for sportnumerics frontend
    Value:
      Ref: CloudfrontDistribution
